# Site settings
title: Roy
email: 237818280@qq.com
description: a great man
baseurl: ""
url: "http://nandomoreira.me"

author:
  name     : 'Roy Yang'
  email    : 237818280@qq.com
  url      : http://nandomoreira.me
  facebook : ''
  twitter  : ''

github: https://github.com/yangrongkai
disqus_shortname: "fernandomoreira"
google_analytics: UA-52446115-1

paginate: 2
comments: true
# paginate_path: "/page/:num"
paginatepath: ['topics/bcycle/page/:num', 'topics/work/page/:num', 'topics/team/page/:num','topics/init/page/:num']

sass:
  style: :compressed
  sass_dir: _sass

# Build settings
markdown  : kramdown
# permalink : /:title/


# config plugins
# gems: [jekyll-paginate-plugin]
